### ISSUE TITLE
Issue with non ISO 639-1 languages codes

### ISSUE THREAD

**Issue by s1-ranjan** [FriendsOfFlarum/discussion-language#16]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Issue while using [Bihari languages](https://en.wikipedia.org/wiki/Bihari_languages) as an option because [Bihari languages](https://en.wikipedia.org/wiki/Bihari_languages) is a subgroup of the Indo-Aryan languages consisting of [Bhojpuri](https://en.wikipedia.org/wiki/Bhojpuri_language), [Magahi](https://en.wikipedia.org/wiki/Magahi_language) and [Maithili](https://en.wikipedia.org/wiki/Maithili_language).

**Describe the solution you'd like**

As of now, this plugin is using [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) codes languages, it would be great if this plugin is allowed to use [ISO 639-2](https://en.wikipedia.org/wiki/ISO_639-2) or [ISO 639-3](https://en.wikipedia.org/wiki/ISO_639-3) languages for those languages who don't have  [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) code.

**Comment by datitisev** [comment]
This feature request has made my life miserable trying to find packages that have all ISO 639 2 alongside native & english names... I have ended up just exporting the wikipedia table to a CSV.

See #19

**Comment by datitisev** [comment]
Added in `v.1.1.0` (#19)
