### ISSUE TITLE
Loading/reloading the page from /all breaks the selected language filter

### ISSUE THREAD

**Issue by iamdarkle** [FriendsOfFlarum/discussion-language#17]
## Bug Report

As the title says, loading/reloading the page from `forum.com/all` breaks the selected language filter, for some reason the filter is broken and loads another language/s.

It is important to emphasize that this only happens from the `/all` page, in my case I have noticed it easily since I use a different home page and I have to access the forum through `/all` the problem is constant and is quite annoying.

I have been able to reproduce the error in any Flarum instance, here I leave 2 examples: [example1](https://community.upc.ch/all ) and [example2 ](https://brickdose.com/all)

**Comment by datitisev** [comment]
This happens to me on both /all and / with the following options:

![image](https://user-images.githubusercontent.com/6401250/129414925-d3289990-fc1b-472f-9740-fc64a541dd38.png)

The dropdown shows "English" even though what it should say was "no language selected" or something similar. I have a feeling this was introduced by #15.

**Comment by iamdarkle** [comment]
Oh ok, for me in / it's a bit random, maybe it's due to my cache (?) so do you think this is also related? I reported it in the Blog extension thinking it was a problem of the blog extension, now I doubt https://github.com/v17development/flarum-blog/issues/94 

In the blog when going backwards the language filter disappears, in fact, the dropdown is empty and thus no posts are shown as all posts have a language assigned to them:


![](https://user-images.githubusercontent.com/15818451/124539014-f7a26e00-de1c-11eb-973c-dff4bda3fbc8.jpg)

**Comment by datitisev** [comment]
Did not mean to close this issue, look like i referenced the wrong one.

**Comment by iamdarkle** [comment]
I've been testing a bit, as far as I could see with version 1.0.0 of the extension which was before https://github.com/FriendsOfFlarum/discussion-language/pull/15 also produced this error, I tried on an old test site with beta 16 and it also happens so I cannot say at what point the error was introduced.

With this I guess the blog error (mentioned above) is a blog extension thing(?) as this error appeared from 1.0 onwards, in beta 16 this didn't happen.

**Comment by imorland** [comment]
This issue requires fixes in several areas. I have the fix locally for this extension, which I'll push later today, but it also depends on https://github.com/flarum/core/pull/3037 and https://github.com/flarum/tags/pull/141

These will _likely_ be included in the next scheduled release from the core team 🤞

**Comment by iamdarkle** [comment]
It looks like those changes were merged in 1.1, does that mean it's been fixed? I haven't updated yet in the environment where I use this extension, I'll try to update on this when I do so I won't forget to close the issue if it's fixed.

**Comment by iamdarkle** [comment]
Yesterday I started to test `1.2.0` with two languages English and Spanish and it seemed that there was still something wrong, mainly what I experienced was 

The language detection was different from the language selector of the page (language pack), for example, all the discussions appeared in Spanish when the default language pack of the page is English, but this was only for the first posts, when I clicked on "Load more" they did appear in English.

The language detection is around the language selected in the language pack selector (core)? or is it based on something else?

**Comment by iamdarkle** [comment]
Sorry @imorland I didn't notice that `1.2.1` had been released, I noticed it now when I did a `composer update` by chance, I don't know very well what this update fixed, but by updating the problems mentioned in my last comment have disappeared, thank you very much for fixing this annoying problem! I close the issue.

**Comment by iamdarkle** [comment]
I'm not sure what is wrong here but eventually I keep experiencing weird things with this. I'm not able to describe exactly what to do as it seems to be pretty random, but every now and then when entering the /all page the discussions appear in mixed languages again, some users especially have notified me that they have experienced this in Firefox. On the other hand, `flarum/sticky` doesn't seem to work and causes problems as the pinned discussions are shown in all languages, even though it defaults to English.

**Comment by datitisev** [comment]
`1.2.3` may have addressed some of these issues? Unsure. There seem to be a lot of different things discussed in this issue as well.

**Comment by iamdarkle** [comment]
Ok, thanks, I will look into this when I upgrade to the latest version, honestly tracing the specific cause or steps to reproduce this has been really complicated during these months... as you say this problem already contains a lot of things, probably if the issue continues I will close this and open a new one.
