### ISSUE TITLE
Language filter breaks when navigating internal links (Toggle "Any Language" enabled)

### ISSUE THREAD

**Issue by iamdarkle** [FriendsOfFlarum/discussion-language#24]
## Bug Report

The new language filter via URL works really well, but some users have reported me several problems that I think are all related, it sounds to me like a SPA bug with the new filter because it always happens with all kind of internal links.

What I mean by broken is that it doesn't pass any value via URL `?language=en`

Examples that cause the filter to break:

- Using `fof/links` to `/all` as an internal link (if we mark this same link as external it does the full reload and applies the filter correctly).
- When entering `/tags`, `/members`, `/following`... when returning to `/all`, `/t/tagexample`... the filter will be broken until a full reload of the page is done.
- When changing the language selector of the site, the URL remains the same `all?language=en` so even if the interface has the language changed, the dicussions appear in the previous language, in this case it does not help to make F5 to the page, as it still reloads the URL with the previous language and will continue without changing the language, so you have to delete it manually from the URL.

There are some other cases, but they are very similar to the first two.

**Environment**
- Flarum version: 1.1.1

**Comment by s1-ranjan** [comment]
I tried to disable this plugin and re-enabling this plugin, but it does not show any option in the setting.

**Comment by s1-ranjan** [comment]
ISO 639-2 or ISO 639-2 are not showing in the frontend.

**Comment by datitisev** [comment]
@s1-ranjan This seems like a separate issue? Is it related to links in the forum side?

**Comment by datitisev** [comment]
Think this may have been fixed with some of the v1.2.x updates. Could you check again? Thanks.

**Comment by iamdarkle** [comment]
From what I have tried so far it seems to be fixed, thank you!
