### ISSUE TITLE
Incompatibility with flarum/sticky

### ISSUE THREAD

**Issue by iamdarkle** [FriendsOfFlarum/discussion-language#31]
## Bug Report

The `flarum/sticky` extension stops working properly in discussions when this extension is activated, sticky posts are lost chronologically among new posts, not only for users (without having seen the post), but also for guests.

**Comment by clarkwinkelmann** [comment]
The Sticky extension essentially disables itself as soon as any search of filter is applied to a view. With this extension enabled, this means Sticky almost always disables itself.

Sticky has an explicit whitelist for `TagFilterGambit`. Ideally we should have a way to plug `LanguageFilterGambit` into that whitelist... But Flarum doesn't have any API to achieve that at the moment.

https://github.com/flarum/framework/blob/v1.5.0/extensions/sticky/src/PinStickiedDiscussionsToTop.php#L27-L37

The only workaround would be to re-implement the whole `PinStickiedDiscussionsToTop` for when a language filter is active in this extension... I think the work would be better put on core to make the whitelist extensible.
